# Generated by Django 6.0.6 on 2026-06-15 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_per_currency', models.DecimalField(decimal_places=2, default=200.0, help_text='Amount to spend to earn 1 point', max_digits=10)),
                ('min_redemption_points', models.PositiveIntegerField(default=50, help_text='Minimum points required to redeem')),
                ('max_redemption_percent', models.DecimalField(decimal_places=2, default=50.0, help_text='Max percentage of an order total that can be discounted', max_digits=5)),
                ('point_value_in_currency', models.DecimalField(decimal_places=2, default=1.0, help_text='Currency value of 1 point when redeeming', max_digits=10)),
            ],
            options={
                'verbose_name': 'Loyalty Configuration',
                'verbose_name_plural': 'Loyalty Configuration',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='points_earned',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='points_redeemed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='LoyaltyWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(default=0)),
                ('total_earned', models.PositiveIntegerField(default=0)),
                ('total_redeemed', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoyaltyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('transaction_type', models.CharField(choices=[('Earned', 'Earned'), ('Redeemed', 'Redeemed'), ('Adjusted', 'Adjusted'), ('Expired', 'Expired'), ('Refunded', 'Refunded')], max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_transactions', to='store.order')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='store.loyaltywallet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
